### PR TITLE
update vsphere_vm_clone.rb for thinProvisioned

### PR DESCRIPTION
**Pull request by tcicone**
option :thin_provision,
         :long => "--thin-provision",
         :description => "Indicates whether disk should be thin provisioned.",
         :boolean => true

    if get_config(:thin_provision)
      rspec = RbVmomi::VIM.VirtualMachineRelocateSpec(:transform => :sparse, :pool => find_pool(get_config(:resource_pool)))
    end

### CODE REVIEW

**Comment by swalberg** [comment]
This is already in the code, is it not? I'm going to close this, but if I made a mistake please let me know and we can figure out where to go from there.

**Comment by tcicone** [comment]
I updated the code, not sure if it was committed?

Thanks.

**Comment by swalberg** [comment]
Yes, we have a `--thin-provision` option in both clone and move.

**Comment by tcicone** [comment]
Cool thanks, I had made some other tweaks to these, I don’t know if they were committed.

vsphere_datastore_list.rb
vsphere_datastorecluster_list
vsphere_vm_list.rb
vsphere_vm_snapshot.rb

Really appreciate everyone’s work on this plugin, it’s worked out very well for us.

Thanks.

**Comment by swalberg** [comment]
Yea, I think b0cf5a4 is where all your work is. This pull request is a bit odd because it's merging stuff out of master into another branch, maybe to package stuff up for a preview release judging by the name.

**Pull request closed without merging**
