### PR TITLE
Windows bootstrap support

### PR DESCRIPTION
**Pull request by tim95030**
I have implemented a working windows bootstrap option. I have verified windows bootstrap over winrm works as does ssh boostrap of linux. This project could desperately use some unit tests but I unfortunately did not have time. I have cleaned up some code as well and tried to make my commits very clear on their actions. Any questions please let me know.

### CODE REVIEW

**Comment by swalberg** [comment]
Did you want to work with me on getting unit tests in to make such refactoring easier?

**Comment by tim95030** [comment]
I don't know if I have much time but I might spend some today looking into it.

**Comment by tim95030** [comment]
Rebased this to current master to resolve conflict.

**Comment by tim95030** [comment]
This is fully working with windows. Is there any reason we cannot merge this? I need this code to use this project so currently I am having to merge in all the changes when I want any fixes or updates. At this point I think it is at least ready for any review comments etc. I am happy to answer any questions. The only issue with it at this point is I still cannot find a good way to determine when sysprep finishes. Vmware has a event that appears, but I have thus far been able to find a useful way to check for that event. If anyone knows rbvmomi well enough to check events for a given vm then all that needs to happen is wait for an even with the description:

Customization of VM $vmame succeeded. 

Anyways please let me know if there is a reason not to merge this.

**Comment by swalberg** [comment]
Hi Tim sorry this one has been dragging on. Frankly this project has no tests and the Windows stuff is so far out of my comfort zone and I don't have the experience to try this one out. My main concern is that we don't introduce problems for existing Linux users, which I suppose is easy enough to verify.

Can you rebase and squash this? I have a couple of Linux boxen to build this week so I'll try it out. Anyone else able to give this a go and provide feedback?

**Comment by swalberg** [comment]
Just created a Linux VM and it didn't blow up my cluster. Would love it if someone else could check and/or provide some comments on the code.

**Comment by tim95030** [comment]
I will see what I can do to rebase it and clean it up the commits. I am also going to fix the sysprep portion. Though you mentioned making it a module. I am a bit confused by that since all of the other commands regarding find in folder etc are all in the base. Are you just wanting it in its own module since not every command needs it?

**Comment by swalberg** [comment]
Yea, the module is to try and avoid the base class from being a junk drawer. I'm not against putting it in the base class if it makes the effort easier -- it's easy enough to extract later if it makes sense. But I think you should coordinate with @mheidenr so we can figure out how to get both of these changes in with a minimum of fuss and a relatively clean history.

**Comment by swalberg** [comment]
One option, if @mheidenr is ok with a bit more work would be for you to rebase this PR as-is (i.e. with the `sleep`), we merge it, and he does his extraction (optionally changing out the `sleep`) on top.

**Comment by tim95030** [comment]
I did a rebase this morning but got busy with work and didn't have a chance
to push up the final changes.  I will get that done tomorrow and leave it
as is regarding the sleep.

**Comment by swalberg** [comment]
When you're rebasing can you squash it down to one commit, please?

**Comment by tim95030** [comment]
Pull request rebased, squashed, and cleaned up to pass rubocop. I did leave the sleep. So that should be replaced as soon as possible.

**Comment by swalberg** [comment]
Merging! cc/ @mheidenr 

BTW I recently got access to push this gem, so when we get this done I can cut a release.

**Comment by tim95030** [comment]
Unfortunately I accidentally broke one thing when I fixed the things rubocop was complaining about it is complaining about using {} on a multi line block, but I think you have to with proc. Either way it doesn't work with the current code, so please grab my new pull request. I apologize for that. I tested it before the cleanup, and the cleanup was almost entirely double quote fixes.

**Pull request merged**
